name: Create tag
on:
  pull_request:
    branches:
      - master

jobs:
 steps:
  - name: Convert JSON to CSV using YML
    uses: your-username/convert-json-to-csv-yml@v1.0.0
    with:
     json-file: 'test.json'
     csv-file: 'path/to/output.csv'
